# Generated by Django 3.0.8 on 2020-07-03 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eBookName', models.CharField(default='', max_length=200)),
                ('eBookFile', models.FileField(upload_to='documents/%Y/%m/%d')),
                ('eBookData', models.TextField(blank=True, default='', editable=False, null=True)),
                ('createdDatetime', models.DateTimeField(auto_now_add=True)),
                ('updatedDatetime', models.DateTimeField(auto_now=True)),
                ('addedBy', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
