# Generated by Django 3.0.7 on 2020-06-30 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='body',
            field=models.TextField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='document',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
