# Generated by Django 3.0.8 on 2020-07-03 08:23

from django.db import migrations, models
import posts.validators


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='eBookFile',
            field=models.FileField(upload_to='documents/%Y/%m/%d', validators=[posts.validators.validate_file_extension]),
        ),
    ]
